### ISSUE TITLE
slowmoVideo doesn't compile with opencv-4.1.2

### ISSUE THREAD

**Issue by HJarausch** [slowmoVideo/slowmoVideo#164] opened 2019-12-09 15:50 UTC
There are problems with (e.g.)
src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:264:15: 
error: 'class cv::DenseOpticalFlow' has no member named 'set'
  264 |         tvl1->set("lambda", lambda);

(On Gentoo Linux with opencv-4.1.2 installed)

**Comment by alexmyczko** [comment] 2020-01-27 11:22
there's a patch for that? https://github.com/slowmoVideo/slowmoVideo/issues/157

**Comment by Granjow** [comment] 2020-04-18 09:40
Closing as duplicate of #157

**Closed by Granjow** 2020-04-18 09:40 UTC
Labels: duplicate
